# Generated by Django 4.0.4 on 2022-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url_to', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
