# Generated by Django 4.0.4 on 2022-06-28 09:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Country name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Country name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Lang')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='User Lang')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='User Lang')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Category')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Category')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug Category')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('base', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_children', to='app.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Категория',
            },
        ),
    ]
